version: "3.9"
services:
  db:
    image: mariadb:11
    restart: always
    environment:
      MARIADB_DATABASE: ${MARIA_DB}
      MARIADB_USER: ${MARIA_USER}
      MARIADB_PASSWORD: ${MARIA_PASSWORD}
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: "yes"
    volumes:
      - mariadb_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

  server:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "3001:3000"
    env_file:
      - .env
    restart: always
    environment:
      MARIA_HOST: db
      MARIA_PORT: 3306
      MARIA_DB: ${MARIA_DB}
      MARIA_USER: ${MARIA_USER}
      MARIA_PASSWORD: ${MARIA_PASSWORD}
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./arquivos_simuladores:/plataforma/server/arquivos_simuladores

volumes:
  mariadb_data:
  arquivos_simuladores: