version: "3.9"
services:
  reverse-proxy:
    image: traefik:v3
    restart: always
    command:
      - "--api.dashboard=true"
      - "--api.insecure=true" #REMOVE IT IN PRODUCTION
      - "--providers.docker"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  db:
    image: mariadb:11
    environment:
      MYSQL_DATABASE: ${MARIA_DB}
      MYSQL_USER: ${MARIA_USER}
      MYSQL_PASSWORD: ${MARIA_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MARIA_ROOT_PASSWORD}
    volumes:
      - mariadb_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

  server:
    build:
      dockerfile: Dockerfile
      context: .
    expose:
      - 3000
    env_file:
      - .env 
    environment:
      MARIA_HOST: db
      MARIA_PORT: 3306
      MARIA_DB: ${MARIA_DB}
      MARIA_USER: ${MARIA_USER}
      MARIA_PASSWORD: ${MARIA_PASSWORD}
    depends_on:
      db:
        condition: service_healthy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.server.rule=Host(`${APP_HOST}`)"
      - "traefik.http.routers.server.entrypoints=web"
      - "traefik.http.services.server.loadbalancer.server.port=3000"
  
  wordpress:
    image: wordpress:php8.5
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: ${WORDPRESS_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB}
    depends_on:
      db:
        condition: service_healthy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wordpress.rule=Host(`${WORDPRESS_HOST}`)"
      - "traefik.http.routers.wordpress.entrypoints=web"
      - "traefik.http.services.wordpress.loadbalancer.server.port=80"

volumes:
  mariadb_data: